version: '3.8'

services:
  shopware:
    image: dockware/dev:latest
    container_name: shopware-app
    ports:
      - "80:80"
      - "3307:3306"
      - "22:22"
      - "8888:8888"
      - "9999:9999"
    volumes:
       - "db_volume:/var/lib/mysql"
       - "shop_volume:/var/www/html"
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=1
      - PHP_VERSION=8.2

volumes:
  db_volume:
    driver: local
  shop_volume:
    driver: local

networks:
  web:
    driver: bridge



